[book]
language = "en"
multilingual = false
src = "."
title = "gote Documentation"

[output.html]
git-repository-url = "https://github.com/kmdkuk/gote"
edit-url-template = "https://github.com/kmdkuk/gote/edit/main/docs/{path}"
site-url = "/goct/"
